export const mockDiscoveryPool = {
  dt: '2023-09-22T05:51:54.275Z',
  current_page: 1,
  list: [
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: null,
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: '',
        number_of_nodes: '',
        dcms: false,
        location: '',
        rackmount_size: '',
        drawer_type: '',
        mon: false,
        system_serial: '',
        bios_version: '',
        attr_state: {
          state: 'Unauthorized',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '',
        product_family: '',
        manufacturer: '',
      },
      usedby: {},
      type: 'unauth',
      state: 'discovered',
      ipv4: '172.24.169.67',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:05:9c:34',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-220H-TN24R',
        number_of_nodes: '',
        dcms: false,
        location: '',
        rackmount_size: '',
        drawer_type: '',
        mon: false,
        system_serial: '',
        bios_version: '1.5',
        attr_state: {
          state: 'sku_mismatch',
          data: {
            sku: 'SYS-220H-TN24R',
          },
        },
        password: 'ADMIN',
        bmc_version: '01.01.43',
        product_family: '',
        manufacturer: '',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.75',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:30:a0:bf',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-621BT-DNTR',
        number_of_nodes: '2',
        dcms: true,
        location: 'C',
        rackmount_size: '2',
        drawer_type: 'TF',
        mon: true,
        system_serial: 'S279266X8B02799',
        bios_version: '1.4',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.00.29',
        product_family: 'Twin Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.117',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:30:78:3e',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-120U-TNR',
        number_of_nodes: '1',
        dcms: true,
        location: '1',
        rackmount_size: '1',
        drawer_type: 'SN',
        mon: true,
        system_serial: 'S372878X9517039',
        bios_version: '1.6',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.03.03',
        product_family: 'Ultra Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.106',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '3c:ec:ef:df:e0:8b',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'AS -1125HS-TNR',
        number_of_nodes: '1',
        dcms: true,
        location: '1',
        rackmount_size: '1',
        drawer_type: 'SN',
        mon: true,
        system_serial: 'S445387X1C11749',
        bios_version: '1.3',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.00.15',
        product_family: 'Hyper Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.74',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:30:05:20',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-221BT-DNTR',
        number_of_nodes: '2',
        dcms: true,
        location: 'A',
        rackmount_size: '2',
        drawer_type: 'TF',
        mon: false,
        system_serial: 'S498093X2704403',
        bios_version: '1.0a',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.00.18',
        product_family: 'Twin Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.111',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:30:04:5e',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-221BT-DNTR',
        number_of_nodes: '2',
        dcms: true,
        location: 'C',
        rackmount_size: '2',
        drawer_type: 'TF',
        mon: false,
        system_serial: 'S498093X2704403',
        bios_version: '1.0a',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.00.18',
        product_family: 'Twin Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.112',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: null,
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: '',
        number_of_nodes: '',
        dcms: false,
        location: '',
        rackmount_size: '',
        drawer_type: '',
        mon: true,
        system_serial: '',
        bios_version: '',
        attr_state: {
          state: 'Unauthorized',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '',
        product_family: '',
        manufacturer: '',
      },
      usedby: {},
      type: 'unauth',
      state: 'discovered',
      ipv4: '172.24.169.72',
    },
    {
      state_ui: 'discovered',
      workstation: '0',
      mac: '7c:c2:55:35:27:e8',
      dt: '2023-09-22T05:51:54.000Z',
      attr: {
        username: 'ADMIN',
        system_model: 'SYS-621BT-HNTR',
        number_of_nodes: '4',
        dcms: true,
        location: 'B',
        rackmount_size: '2',
        drawer_type: 'TF',
        mon: true,
        system_serial: 'S732243X8B02799',
        bios_version: '1.0a',
        attr_state: {
          state: 'ok',
          data: null,
        },
        password: 'ADMIN',
        bmc_version: '01.00.18',
        product_family: 'Twin Family',
        manufacturer: 'Supermicro',
      },
      usedby: {},
      type: 'bmc',
      state: 'discovered',
      ipv4: '172.24.169.77',
    },
  ],
  total_page: 1,
  entries: 30,
}